### ISSUE TITLE
Frontent build command does not work on master

### ISSUE THREAD

**Issue by amercader** [ckan/ckan#3688]
Running `paster front-end-build` on master returns:

```
Traceback (most recent call last):
  File "/home/adria/dev/pyenvs/ckan/bin/paster", line 11, in <module>
    sys.exit(run())
  File "/home/adria/dev/pyenvs/ckan/local/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/home/adria/dev/pyenvs/ckan/local/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/home/adria/dev/pyenvs/ckan/local/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/home/adria/dev/pyenvs/ckan/src/ckan/ckan/lib/cli.py", line 2120, in command
    cmd.command()
  File "/home/adria/dev/pyenvs/ckan/src/ckan/ckan/lib/cli.py", line 2025, in command
    self._load_config()
  File "/home/adria/dev/pyenvs/ckan/src/ckan/ckan/lib/cli.py", line 310, in _load_config
    self.site_user = load_config(self.options.config, load_site_user)
AttributeError: 'LessCommand' object has no attribute 'options'
```

Looks like the culprit is this [line](https://github.com/ckan/ckan/pull/3547/files#diff-530e98d83857b6bd57795518ad4c2dbdR2027), part of the Bootstrap 3 PR.

@klikstermkd can you have a look?

**Comment by amercader** [comment]
This works on 2.7 so there's no rush

**Comment by klikstermkd** [comment]
@amercader Yes I will look into it.
