### ISSUE TITLE
Backwards compatibility of templates using "c"

### ISSUE THREAD

**Issue by metaodi** [ckan/ckan#4498]
### CKAN Version if known (or site URL)
Current master

### Please describe the expected behaviour
It should be possible to use the same template from 2.8 in the current master, without having to deal with missing variables in `c`.

### Please describe the actual behaviour
I have an extension that overrides the `organization/index.html` page, it is based on the template from CKAN 2.8.1. Therefore some variables from `c` are used, e.g.:

```
<h2><span class="result-count">{{ c.page.item_count }}</span></h2>
```

In CKAN 2.8.1 this works perfectly, but when [running my tests on the current master, it fails](https://travis-ci.org/opendata-swiss/ckanext-switzerland/jobs/441573420#L1332):

```
UndefinedError: 'werkzeug.local.LocalProxy object' has no attribute 'page'
``` 

### What steps can be taken to reproduce the issue?
1. Override the organization/index.html template and access `c.page` in the template
2. Try to render the template using the latest master

**Comment by metaodi** [comment]
I think this "error" was introduced in #4143, since the group view does not expose the old variables in `g`. Now I'm not sure if the goal is actually to be able to use a 2.8 template 1:1 in the current master.

A simple workaround would be to start the template with:

```
{% if c.page %}
   {% set page = c.page %}
{% endif %}
```
And then simply use `page` in this template. I'm just not sure if this is what you want.
Shouldn't there be at least one release that supports both worlds?

cc @amercader @tino097

**Comment by tino097** [comment]
Thanks @metaodi, it looks that i need to add the `page` to `g` variable as it was done [here](https://github.com/tino097/ckan/blob/5d051d01edea0e82ac1a1cab3e5870890bd9793f/ckan/views/group.py#L179).

**Comment by wardi** [comment]
@metaodi my mistake, I apologise! I think we have have added some `c` backwards compatibility fixes like the one @tino097 linked.

A better comment with the code would be great though. e.g.
```python
# ckan 2.9: Adding variables that were removed from c object for 
# compatibility with templates in existing extensions
```
