### ISSUE TITLE
SQLAlchemy Session error when updating a resource

### ISSUE THREAD

**Issue by quinoescobar** [ckan/ckan#6644]
**CKAN version**
2.9.4

**Describe the bug**
I just update from 2.9.3 to 2.9.4 release in my testing server and when I try to update a resource by API call or by web the ckan gives a timeout error.

**Steps to reproduce**
Use version 2.9.4, log in and in an existing dataset try to reload a new version of the file a resource has, then update the resource, and starting this moment the app stops working properly till the ckan instance is restarted.

**Expected behavior**
 not failing 

**Additional details**
This is the traceback, it looks like a session scope problem : 

```
DEBUG [ckan.logic] check access OK - package_update user=xxxx
DEBUG [ckan.logic] check access OK - resource_update user=xxxx
DEBUG [ckan.logic] check access OK - package_show user=xxxx
DEBUG [ckan.lib.search.query] Package query: {'rows': 1, 'q': 'name:"8a8de3cb-13bd-462e-9f9d-0db736c64052" OR id:"8a8de3cb-13bd-462e-9f9d-0db736c64052"', 'wt': 'json', 'fq': 'site_id:"default"'}
DEBUG [ckan.logic] check access OK - package_update user=xxxx
DEBUG [ckan.logic.action.update] package_update validate_errs={} user=xxxx package=xxx-xxx data={'author': '', 'author_email': '', 'id': '8a8de3cb-13bd-462e-9f9d-0db736c64052', 'license_id': '', 'maintainer': '', 'maintainer_email': '', 'name': 'xxxx', 'notes': '', 'owner_org': 'e79beced-a056-4b6b-bdc7-ef3bae870c9e', 'private': False, 'state': 'active', 'title': 'xxxx', 'type': 'dataset', 'url': '', 'version': '', 'resources': [{'created': datetime.datetime(2021, 12, 1, 11, 46, 57, 673097), 'datastore_active': True, 'datastore_contains_all_records_of_source_file': False, 'description': '', 'format': 'ODS', 'hash': '24ef88fbb12386fb1c837ef019f793fe', 'id': '5597ff59-7fc7-4bf1-97aa-eca6415496d4', 'last_modified': datetime.datetime(2021, 12, 1, 14, 8, 28, 990026), 'metadata_modified': '2021-12-01T15:44:22.573862', 'mimetype': 'application/vnd.oasis.opendocument.spreadsheet', 'name': 'xxxx', 'size': 4175, 'url': 'xxxx/ods.ods', 'url_type': 'upload'}, {'ckan_url': 'https://xxx', 'created': datetime.datetime(2021, 12, 1, 15, 44, 22, 582206), 'datastore_active': True, 'datastore_contains_all_records_of_source_file': True, 'description': '', 'format': 'PNG', 'hash': '24ef88fbb12386fb1c837ef019f793fe', 'id': '58268a4d-dcbb-43f8-8923-d39e5a3cd394', 'ignore_hash': False, 'last_modified': datetime.datetime(2021, 12, 1, 15, 45, 28, 855231), 'metadata_modified': '2021-12-01T15:45:41.903310', 'mimetype': 'application/vnd.oasis.opendocument.spreadsheet', 'name': 'xxxx', 'original_url': 'xxxx/ods.ods', 'resource_id': '58268a4d-dcbb-43f8-8923-d39e5a3cd394', 'set_url_type': False, 'size': 4175, 'task_created': '2021-12-01 15:45:39.992795', 'url': 'xxxx/ods.ods', 'url_type': 'upload'}, {'ckan_url': 'https://xxxx', 'created': datetime.datetime(2021, 12, 1, 15, 46, 51, 478975), 'datastore_active': True, 'datastore_contains_all_records_of_source_file': True, 'description': '', 'format': 'PNG', 'hash': 'e03fcf23edded2f388d9be7eb722afeb', 'id': '2ab818f3-faac-49c3-95da-ad0a8f634340', 'ignore_hash': False, 'last_modified': datetime.datetime(2021, 12, 1, 15, 47, 9, 809567), 'metadata_modified': '2021-12-01T15:47:27.321522', 'mimetype': 'text/csv', 'name': 'xxxx', 'original_url': 'xxxx/csv.csv', 'resource_id': '2ab818f3-faac-49c3-95da-ad0a8f634340', 'set_url_type': False, 'size': 83, 'task_created': '2021-12-01 15:47:25.501774', 'url': 'xxxx/csv.csv', 'url_type': 'upload'}, {'created': datetime.datetime(2021, 12, 2, 10, 41, 33, 948792), 'datastore_active': False, 'datastore_contains_all_records_of_source_file': False, 'description': '', 'format': 'ODS', 'hash': '', 'id': '7313cb40-29b8-4b1c-b31b-dd681c2765ff', 'last_modified': datetime.datetime(2021, 12, 2, 10, 41, 33, 913066), 'metadata_modified': '2021-12-14T15:55:21.973437', 'mimetype': 'application/vnd.oasis.opendocument.spreadsheet', 'name': 'xxxx', 'size': 4175, 'url': 'xxxx/ods.ods', 'url_type': 'upload'}, {'ckan_url': 'xxxx', 'created': datetime.datetime(2021, 12, 14, 15, 55, 21, 994394), 'datastore_active': True, 'datastore_contains_all_records_of_source_file': True, 'description': '', 'format': 'CSV', 'hash': '64f65cd7b49a07eed9b6b79f393e4d71', 'id': 'f6706477-8db3-4aeb-bc03-9102a17be308', 'ignore_hash': True, 'last_modified': datetime.datetime(2021, 12, 14, 15, 55, 21, 943098), 'metadata_modified': '2021-12-14T15:55:25.944995', 'mimetype': 'text/csv', 'name': 'xxxx', 'original_url': 'xxxx/xxxx.csv', 'resource_id': 'f6706477-8db3-4aeb-bc03-9102a17be308', 'set_url_type': False, 'size': 3504, 'task_created': '2021-12-14 15:55:22.431700', 'url': 'xxxx/xxxx.csv', 'url_type': 'upload'}, {'datastore_active': True, 'description': '', 'format': 'CSV', 'id': '5c5d9b00-df67-4e85-844d-c66547675ad6', 'last_modified': datetime.datetime(2022, 1, 11, 12, 43, 43, 347614), 'mimetype': 'text/csv', 'name': 'xxxx', 'size': 113, 'url': 'csv.csv', 'url_type': 'upload'}], 'tags': [], 'extras': [], 'groups': [], 'relationships_as_subject': [], 'relationships_as_object': []}
DEBUG [ckan.logic] check access OK - package_owner_org_update user=xxxx
DEBUG [ckan.logic] check access OK - package_show user=xxxx
DEBUG [ckan.lib.search.query] Package query: {'rows': 1, 'q': 'name:"8a8de3cb-13bd-462e-9f9d-0db736c64052" OR id:"8a8de3cb-13bd-462e-9f9d-0db736c64052"', 'wt': 'json', 'fq': 'site_id:"default"'}
DEBUG [ckan.logic] check access OK - resource_show user=xxxx
DEBUG [ckan.logic] check access OK - package_show user=xxxx
DEBUG [ckan.lib.search.query] Package query: {'rows': 1, 'q': 'name:"8a8de3cb-13bd-462e-9f9d-0db736c64052" OR id:"8a8de3cb-13bd-462e-9f9d-0db736c64052"', 'wt': 'json', 'fq': 'site_id:"default"'}
DEBUG [ckan.logic] check access OK - task_status_show user=xxxx
DEBUG [ckanext.xloader.plugin] Submitting resource 5c5d9b00-df67-4e85-844d-c66547675ad6 to be xloadered
DEBUG [ckan.logic] check access OK - xloader_submit user=xxxx
DEBUG [ckan.logic] check access OK - resource_show user=xxxx
DEBUG [ckan.logic] check access OK - package_show user=xxxx
DEBUG [ckan.lib.search.query] Package query: {'rows': 1, 'q': 'name:"8a8de3cb-13bd-462e-9f9d-0db736c64052" OR id:"8a8de3cb-13bd-462e-9f9d-0db736c64052"', 'wt': 'json', 'fq': 'site_id:"default"'}
DEBUG [ckan.logic] check access OK - get_site_user user=xxxx
DEBUG [ckan.logic] check access OK - task_status_show user=xxxx
DEBUG [ckan.lib.jobs] Initializing background job queue "default"
INFO  [ckanext.xloader.action] A pending task was found '44e90ce0-cd75-4f5d-b770-ae6ffb192c18', but its not found in the queue [] and is 21:10:20.115139 hours old
DEBUG [ckan.logic] check access OK - task_status_update user=
DEBUG [ckan.logic] check access OK - resource_show user=xxxx
DEBUG [ckan.logic] check access OK - package_show user=xxxx
DEBUG [ckan.lib.search.query] Package query: {'rows': 1, 'q': 'name:"8a8de3cb-13bd-462e-9f9d-0db736c64052" OR id:"8a8de3cb-13bd-462e-9f9d-0db736c64052"', 'wt': 'json', 'fq': 'site_id:"default"'}
DEBUG [ckan.logic] check access OK - task_status_show user=xxxx
DEBUG [ckanext.xloader.plugin] Submitting resource 5c5d9b00-df67-4e85-844d-c66547675ad6 to be xloadered
DEBUG [ckan.logic] check access OK - xloader_submit user=xxxx
DEBUG [ckan.logic] check access OK - resource_show user=xxxx
DEBUG [ckan.logic] check access OK - package_show user=xxxx
DEBUG [ckan.lib.search.query] Package query: {'rows': 1, 'q': 'name:"8a8de3cb-13bd-462e-9f9d-0db736c64052" OR id:"8a8de3cb-13bd-462e-9f9d-0db736c64052"', 'wt': 'json', 'fq': 'site_id:"default"'}
DEBUG [ckan.logic] check access OK - get_site_user user=xxxx
DEBUG [ckan.logic] check access OK - task_status_show user=xxxx
INFO  [ckanext.xloader.action] A pending task was found '44e90ce0-cd75-4f5d-b770-ae6ffb192c18', but its not found in the queue [] and is 21:10:20.195962 hours old
DEBUG [ckan.logic] check access OK - task_status_update user=
ponse headers from daemon process 'ckan_default_ssl': /etc/ckan/default/apache.wsgi, referer: xxxx/dataset/xxxx-xxxx/resource/5c5d9b00-df67-4e85-844d-c66547675ad6/edit
DEBUG [ckan.logic] check access OK - site_read user=
DEBUG [ckan.logic] check access OK - package_search user=
DEBUG [ckan.lib.search.query] Package query: {'facet.field': ['organization', 'groups', 'tags', 'res_format', 'license_id'], 'fq': [' -dataset_type:harvest -dataset_type:showcase', '+site_id:"default"', '+state:active', '+permission_labels:("public")'], 'q': '*:*', 'rows': 21, 'start': 0, 'df': 'text', 'sort': 'score desc, metadata_modified desc', 'fl': 'id validated_data_dict', 'facet': 'true', 'facet.limit': '50', 'facet.mincount': 1, 'wt': 'json'}
DEBUG [ckan.logic] check access NotAuthorized - package_create user= "El usuario  no est\xc3\xa1 autorizado para crear paquetes"
DEBUG [ckan.views] No valid session data - deleting session
DEBUG [ckan.views] Session: dict_items([('_domain', None), ('_path', '/'), ('_accessed_time', 1641908083.3459702), ('_creation_time', 1641908083.3459702)])
INFO  [ckan.config.middleware.flask_app]  200 /dataset render time 0.126 seconds
ERROR [ckan.config.middleware.flask_app] Exception on /webassets/base/4f3188fa_main.css [GET]
Traceback (most recent call last):
  File "/usr/lib/ckan/default/lib64/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/ckan/default/lib64/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/lib/ckan/default/lib64/python3.6/site-packages/flask/app.py", line 1969, in finalize_request
    response = self.process_response(response)
  File "/usr/lib/ckan/default/lib64/python3.6/site-packages/flask/app.py", line 2266, in process_response
    response = handler(response)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/flask_app.py", line 391, in ckan_after_request
    model.Session.remove()
AttributeError: 'Session' object has no attribute 'remove'

2022-01-11 13:34:43,651 INFO  [ckan.config.middleware.flask_app] 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
2022-01-11 13:34:43,680 ERROR [ckan.config.middleware.flask_app] Request finalizing failed with an error while handling an error
Traceback (most recent call last):
  File "/usr/lib/ckan/default/lib64/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/ckan/default/lib64/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/lib/ckan/default/lib64/python3.6/site-packages/flask/app.py", line 1969, in finalize_request
    response = self.process_response(response)
  File "/usr/lib/ckan/default/lib64/python3.6/site-packages/flask/app.py", line 2266, in process_response
    response = handler(response)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/flask_app.py", line 391, in ckan_after_request
    model.Session.remove()
AttributeError: 'Session' object has no attribute 'remove'


```

**Comment by smotornyuk** [comment]
I have the similar issue with ckanext-xloader <= 0.9.0. Can you upgrade ckanext-xloader to the latest version? (or you're already using it?)

**Comment by quinoescobar** [comment]
I'm working with ckanext-xloader V0.9.0 right now because I've had this issue: https://github.com/ckan/ckanext-xloader/issues/148
But just now I saw your reply to that issue.

I'll try CKAN core v2.9.4 with ckanext-xloader V0.10.0, and check both issues.

Thanks

**Comment by quinoescobar** [comment]
@smotornyuk It worked.

Just upgraded to the version 2.9.5 of CKAN with XLoader extension version 0.10.0 and the problem was solved.

Thank you.
