### ISSUE TITLE
CKAN 2.11.5 Not Producing Tracking Summary

### ISSUE THREAD

**Issue by jannettim** [ckan/ckan#9437]
## CKAN version
2.11.5

## Describe the bug
After migrating a site from 2.10 to 2.11.5 and enabling the tracking plugin I cannot export a tracking summary. When I attempt to do so, I get the following error `TypeError: ViewCount.__new__() missing 1 required positional argument: 'count'`.  As far as I can see, the tracking_raw table in the database is updating.

This occurred both on a docker install (clean install on new machine but with an imported database) and on a local test source install (clean install, no previous database imported)

Please let me know if you need any additional information.

### Steps to reproduce
1. Enable the tracking plugin in ckan.ini
2. Update the database `ckan -c ckan.ini db upgrade -p tracking`
3. Run `ckan -c ckan.ini tracking export [file]`

### Expected behavior
A file to be created containing the tracking summary information, including counts of total views and number of recent views in the last 2 weeks.

### Additional details

Here is the stack trace from the docker installation
```
2026-07-21 18:15:40,953 INFO  [ckan.lib.search] Finished rebuilding search index.
search index rebuilding done.
Traceback (most recent call last):
  File "/usr/local/bin/ckan", line 6, in <module>
    sys.exit(ckan())
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/srv/app/src/ckan/ckanext/tracking/cli/tracking.py", line 46, in export
    export_tracking(output_file)
  File "/srv/app/src/ckan/ckanext/tracking/cli/tracking.py", line 123, in export_tracking
    recent_views = _recent_views(measure_from)
  File "/srv/app/src/ckan/ckanext/tracking/cli/tracking.py", line 106, in _recent_views
    return [
  File "/srv/app/src/ckan/ckanext/tracking/cli/tracking.py", line 107, in <listcomp>
    ViewCount(*t) for t in session.execute(stmt)
TypeError: ViewCount.__new__() missing 1 required positional argument: 'count'
```

**Comment by jannettim** [comment]
To consolidate additional information @JVickery-TBS provided on gitter.

They pointed out that ViewCount is a named tuple (https://github.com/ckan/ckan/blob/master/ckanext/tracking/cli/tracking.py#L24)

```python
class ViewCount(NamedTuple):
    id: str
    name: str
    count: int
```
But the query is pulling package_id and total_views.
```python
select(
            ts.package_id,
            func.coalesce(func.sum(ts.count), 0).label("total_views"),
        )
return [ViewCount(*t) for t in session.execute(stmt)]
```
This would only provide the id and name parameters and not the count parameter. They pulled the code from the master branch.
