### ISSUE TITLE
ERROR in app: Exception on /user/login [GET]

### ISSUE THREAD

**Issue by kimepe** [ckan/ckan#4543]
### CKAN Version if known (or site URL)
2.8.1

### Please describe the expected behaviour

- Have access to the login form/page when I go to http://myckanserver/user/login

### Please describe the actual behaviour

- This issue only manifests itself when I activate a custom theme from the plugis section in production.ini. All the other pages are behaving as expected. When I deactivate the plugin and fall back to the default CKAN theme, everything works fine. Can't see how or what is this issue arising
- Get an Internal Server Page Error when attempting to login from the homepage
- This also happens by trying to view the DashBoard (http://myckanserver/user/dashboard)
- All other links work properly so far
- Here is the stack trace. I just have the most recent calls. I would like to know how to show the full stack trace, as it might show where the issue is actually generated

``` 
[Wed Oct 31 15:00:27.096955 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073] [2018-10-31 15:00:27,095] ERROR in app: Exception on /user/login [GET]
[Wed Oct 31 15:00:27.097010 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073] Traceback (most recent call last):
[Wed Oct 31 15:00:27.097015 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
[Wed Oct 31 15:00:27.097035 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]     response = self.full_dispatch_request()
[Wed Oct 31 15:00:27.097037 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
[Wed Oct 31 15:00:27.097039 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]     rv = self.handle_user_exception(e)
[Wed Oct 31 15:00:27.097041 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/flask/app.py", line 1518, in handle_user_exception
[Wed Oct 31 15:00:27.097043 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]     return handler(e)
[Wed Oct 31 15:00:27.097045 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]   File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/flask_app.py", line 424, in error_handler
[Wed Oct 31 15:00:27.097048 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]     return base.render(u'error_document_template.html', extra_vars), 500
[Wed Oct 31 15:00:27.097050 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]   File "/usr/lib/ckan/default/src/ckan/ckan/lib/base.py", line 127, in render
[Wed Oct 31 15:00:27.097052 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]     return flask_render_template(template_name, **extra_vars)
[Wed Oct 31 15:00:27.097053 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
[Wed Oct 31 15:00:27.097055 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]     context, ctx.app)
[Wed Oct 31 15:00:27.097057 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
[Wed Oct 31 15:00:27.097059 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]     rv = template.render(context)
[Wed Oct 31 15:00:27.097061 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
[Wed Oct 31 15:00:27.097063 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]     return self.environment.handle_exception(exc_info, True)
[Wed Oct 31 15:00:27.097079 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
[Wed Oct 31 15:00:27.097081 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]     reraise(exc_type, exc_value, tb)
[Wed Oct 31 15:00:27.097083 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]   File "/usr/lib/ckan/default/src/ckanext-impressivetheme/ckanext/impressivetheme/templates/error_document_template.html", line 4, in top-level template code
[Wed Oct 31 15:00:27.097085 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]     {% if c.code[0] == "404" %}
[Wed Oct 31 15:00:27.097087 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/jinja2/environment.py", line 389, in getitem
[Wed Oct 31 15:00:27.097089 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]     return obj[argument]
[Wed Oct 31 15:00:27.097091 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073] UndefinedError: 'werkzeug.local.LocalProxy object' has no attribute 'code'
[Wed Oct 31 15:00:27.098031 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073] mod_wsgi (pid=3217): Exception occurred processing WSGI script '/etc/ckan/default/apache.wsgi'.
[Wed Oct 31 15:00:27.098062 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073] Traceback (most recent call last):
[Wed Oct 31 15:00:27.098072 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]   File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/__init__.py", line 202, in __call__
[Wed Oct 31 15:00:27.098139 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]     return self.apps[app_name](environ, start_response)
[Wed Oct 31 15:00:27.098153 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/repoze/who/middleware.py", line 86, in __call__
[Wed Oct 31 15:00:27.098274 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]     app_iter = app(environ, wrapper.wrap_start_response)
[Wed Oct 31 15:00:27.098284 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/webob/dec.py", line 147, in __call__
[Wed Oct 31 15:00:27.098339 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]     resp = self.call_func(req, *args, **self.kwargs)
[Wed Oct 31 15:00:27.098348 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/webob/dec.py", line 208, in call_func
[Wed Oct 31 15:00:27.098357 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]     return self.func(req, *args, **kwargs)
[Wed Oct 31 15:00:27.098362 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/fanstatic/publisher.py", line 234, in __call__
[Wed Oct 31 15:00:27.098410 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]     return request.get_response(self.app)
[Wed Oct 31 15:00:27.098421 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/webob/request.py", line 1053, in get_response
[Wed Oct 31 15:00:27.098563 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]     application, catch_exc_info=False)
[Wed Oct 31 15:00:27.098572 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/webob/request.py", line 1022, in call_application
[Wed Oct 31 15:00:27.098580 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]     app_iter = application(self.environ, start_response)
[Wed Oct 31 15:00:27.098584 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/webob/dec.py", line 147, in __call__
[Wed Oct 31 15:00:27.098594 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]     resp = self.call_func(req, *args, **self.kwargs)
[Wed Oct 31 15:00:27.098598 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/webob/dec.py", line 208, in call_func
[Wed Oct 31 15:00:27.098611 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]     return self.func(req, *args, **kwargs)
[Wed Oct 31 15:00:27.098615 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/fanstatic/injector.py", line 54, in __call__
[Wed Oct 31 15:00:27.098640 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]     response = request.get_response(self.app)
[Wed Oct 31 15:00:27.098649 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/webob/request.py", line 1053, in get_response
[Wed Oct 31 15:00:27.098656 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]     application, catch_exc_info=False)
[Wed Oct 31 15:00:27.098660 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/webob/request.py", line 1022, in call_application
[Wed Oct 31 15:00:27.098669 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]     app_iter = application(self.environ, start_response)
[Wed Oct 31 15:00:27.098673 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
[Wed Oct 31 15:00:27.098681 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]     return self.wsgi_app(environ, start_response)
[Wed Oct 31 15:00:27.098685 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/beaker/middleware.py", line 156, in __call__
[Wed Oct 31 15:00:27.098717 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]     return self.wrap_app(environ, session_start_response)
[Wed Oct 31 15:00:27.098726 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
[Wed Oct 31 15:00:27.098733 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]     response = self.handle_exception(e)
[Wed Oct 31 15:00:27.098737 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/flask/app.py", line 1547, in handle_exception
[Wed Oct 31 15:00:27.098743 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]     return self.finalize_request(handler(e), from_error_handler=True)
[Wed Oct 31 15:00:27.098750 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]   File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/flask_app.py", line 424, in error_handler
[Wed Oct 31 15:00:27.098758 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]     return base.render(u'error_document_template.html', extra_vars), 500
[Wed Oct 31 15:00:27.098762 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]   File "/usr/lib/ckan/default/src/ckan/ckan/lib/base.py", line 127, in render
[Wed Oct 31 15:00:27.098772 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]     return flask_render_template(template_name, **extra_vars)
[Wed Oct 31 15:00:27.098778 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
[Wed Oct 31 15:00:27.098789 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]     context, ctx.app)
[Wed Oct 31 15:00:27.098793 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
[Wed Oct 31 15:00:27.098799 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]     rv = template.render(context)
[Wed Oct 31 15:00:27.098803 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
[Wed Oct 31 15:00:27.098809 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]     return self.environment.handle_exception(exc_info, True)
[Wed Oct 31 15:00:27.098841 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
[Wed Oct 31 15:00:27.098849 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]     reraise(exc_type, exc_value, tb)
[Wed Oct 31 15:00:27.098854 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]   File "/usr/lib/ckan/default/src/ckanext-impressivetheme/ckanext/impressivetheme/templates/error_document_template.html", line 4, in top-level template code
[Wed Oct 31 15:00:27.098861 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]     {% if c.code[0] == "404" %}
[Wed Oct 31 15:00:27.098868 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/jinja2/environment.py", line 389, in getitem
[Wed Oct 31 15:00:27.098874 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073]     return obj[argument]
[Wed Oct 31 15:00:27.098884 2018] [wsgi:error] [pid 3217:tid [client 127.0.0.1:64073] UndefinedError: 'werkzeug.local.LocalProxy object' has no attribute 'code'

```

### What steps can be taken to reproduce the issue? 

- activate the custom theme in the plugin section of the production.ini file
- restart Apache
- log into the CKAN server and try to access the Login or Dashboard Page

### Would like to know

- how to force the system to display the full stack trace, not just the most recent calls. Ithink the issue is somewhere hidden in my theme. But the current recent calls do not allow me to see what could be the issue
- how to troubleshoot the cause of the exception related to the WSGI script : Exception occurred processing WSGI script '/etc/ckan/default/apache.wsgi'.

**Comment by rossjones** [comment]
If there's an error elsewhere, it is being disguised by 

```
File "/usr/lib/ckan/default/src/ckanext-impressivetheme/ckanext/impressivetheme/templates/error_document_template.html", line 4, in top-level template code
{% if c.code[0] == "404" %}
```
You should check if the extension sets c.code and if so, what to. If you fix that, it'll be easier to find any underlying problem.

**Comment by kimepe** [comment]
Hi @rossjones. Thanks for pointing it to me. By the way I didn't check it at first because the code, as it is, worked fine on CKAN 2.4. Removing all mentions to c.[attribute] made the login page work again. I had to change the logic of the related pages. Fortunately, it's not a big deal for now.

Thanks once more.
