### ISSUE TITLE
Copy Dataset With Resources Not Working with CKAN 2.10 version

### ISSUE THREAD

**Issue by vj-addnode** [ckan/ckan#7995]
## CKAN version - 2.10.1/2.10.3

**App is broken when trying to create dataset using copy resources feature. Request.endpoint in toolkit.py file inside plugins is coming as none.  I am running CKAN 2.10.1 version on windows local. Below is the complete error detail :-** 

**URL -> 'http://127.0.0.1:5000/dataset/copy/3d2235b4-5dad-401a-baf2-c1b812a86f02/resources'**

 ERROR [ckan.config.middleware.flask_app] Exception on /dataset/copy/3d2235b4-5dad-401a-baf2-c1b812a86f02/resources [POST]
Traceback (most recent call last):
  File "C:\app\src\vckan\Lib\site-packages\flask\app.py", line 1514, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\app\src\vckan\Lib\site-packages\flask\app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(before_func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\app\src\ckan\ckan\config\middleware\flask_app.py", line 427, in ckan_before_request
    set_controller_and_action()
  File "C:\app\src\ckan\ckan\views\__init__.py", line 147, in set_controller_and_action
    g.blueprint, g.view = p.toolkit.get_endpoint()
                          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\app\src\ckan\ckan\plugins\toolkit.py", line 293, in get_endpoint
    blueprint, *rest = cast(str, request.endpoint).split(".", 1)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\app\src\vckan\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\app\src\vckan\Lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\app\src\vckan\Lib\site-packages\flask\app.py", line 1393, in handle_user_exception
    return self.ensure_sync(handler)(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\app\src\ckan\ckan\config\middleware\flask_app.py", line 629, in error_handler
    return base.render(u'error_document_template.html', extra_vars), 500
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\app\src\ckan\ckan\lib\base.py", line 107, in render
    return flask_render_template(template_name, **extra_vars)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\app\src\vckan\Lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
           ^^^^^^^^
  File "C:\app\src\vckan\Lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\app\src\vckan\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\app\src\vckan\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\app\src\ckan\ckan\templates\error_document_template.html", line 1, in top-level template code
    {% extends "page.html" %}
  File "C:\app\src\ckan\ckan\templates\page.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\app\src\vckan\Lib\site-packages\ckanext\geoview\plugin\../templates\base.html", line 1, in top-level template code
    {% ckan_extends %}
  File "C:\app\src\vckan\Lib\site-packages\ckanext\harvest\templates\base.html", line 1, in top-level template code
    {% ckan_extends %}
  File "C:\app\src\ckan\ckan\templates\base.html", line 108, in top-level template code
    {%- block page %}{% endblock -%}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\app\src\ckan\ckan\templates\page.html", line 14, in block 'page'
    {%- block header %}
  File "C:\app\src\ckan\ckan\templates\page.html", line 15, in block 'header'
    {% include "header.html" %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\app\src\vckan\Lib\site-packages\ckanext\saml2auth\templates\header.html", line 1, in top-level template code
    {#
  File "C:\app\src\ckan\ckan\templates\header.html", line 3, in top-level template code
    {% block header_wrapper %} {% block header_account %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\app\src\ckan\ckan\templates\header.html", line 96, in block 'header_wrapper'
    {% block header_site_navigation %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\app\src\ckan\ckan\templates\header.html", line 97, in block 'header_site_navigation'
    {% block header_site_navigation_tabs %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\app\src\ckan\ckan\templates\header.html", line 101, in block 'header_site_navigation_tabs'
    {{ h.build_nav_main(
  File "C:\app\src\ckan\ckan\lib\helpers.py", line 858, in build_nav_main
    output += _make_menu_item(menu_item, title,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\app\src\ckan\ckan\lib\helpers.py", line 960, in _make_menu_item
    active = _link_active(item)
             ^^^^^^^^^^^^^^^^^^
  File "C:\app\src\ckan\ckan\lib\helpers.py", line 744, in _link_active
    blueprint, endpoint = p.toolkit.get_endpoint()
                          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\app\src\ckan\ckan\plugins\toolkit.py", line 293, in get_endpoint
    blueprint, *rest = cast(str, request.endpoint).split(".", 1)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'
2023-12-27 10:16:36,207 INFO  [ckan.config.middleware.flask_app] 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

### Steps to reproduce
Steps to reproduce the behavior: **Go to dataset and click copy. From drop down select with resources. Click Finish.**

**Comment by Zharktas** [comment]
Seems a support request without additional info, can be reopened if it an actual fault in ckan.

**Comment by vj-addnode** [comment]
Sorry for late reply, was on leave. Yeah you are right, we are using an extension and its an internal issue. Thanks.
