### ISSUE TITLE
Error - <type 'exceptions.AttributeError'>: 'list' object has no attribute 'nodes'

### ISSUE THREAD

**Issue by anibalpacheco** [ckan/ckan#1854]
Suggested patch (it worked):

```
diff --git a/ckan/lib/jinja_extensions.py b/ckan/lib/jinja_extensions.py
index a5a1a46..e1d2fa9 100644
--- a/ckan/lib/jinja_extensions.py
+++ b/ckan/lib/jinja_extensions.py
@@ -62,7 +62,10 @@ class CkanInternationalizationExtension(ext.InternationalizationExtension):
 
     def parse(self, parser):
         node = ext.InternationalizationExtension.parse(self, parser)
-        args = getattr(node.nodes[0], 'args', None)
+        if type(node) is list:
+            args = getattr(node[1].nodes[0], 'args', None)
+        else:
+            args = getattr(node.nodes[0], 'args', None)
         if args:
             for arg in args:
                 if isinstance(arg, nodes.Const):
```

**Comment by kishoredhandapani** [comment]
hi i am facing the same issue

[Thu Jun 04 19:11:17 2015] [error] [client 10.212.134.205] File '/usr/lib/ckan/default/src/ckan/ckan/lib/jinja_extensions.py', line 65 in parse
[Thu Jun 04 19:11:17 2015] [error] [client 10.212.134.205]   args = getattr(node.nodes[0], 'args', None)
[Thu Jun 04 19:11:17 2015] [error] [client 10.212.134.205] AttributeError: 'list' object has no attribute 'nodes'

in earlier installation of ckan, i never faced this issue.

**Comment by maxious** [comment]
Also experiencing after upgrading from 2.2 to 2.3.1. Disabled all extensions except datastore text_view recline_view. Reindexed whole site after upgrade. Only applying patch in this ticket resolved the issue.

The affected page is just /dataset/[anydataset]. Full error log: https://gist.github.com/maxious/0218ec0b4a7953d4d54f

```
## Internationalisation Settings
ckan.locale_default = en_GB
ckan.locale_order = en pt_BR ja it cs_CZ ca es fr el sv sr sr@latin no sk fi ru de pl nl bg ko_KR hu sa sl lv
ckan.locales_offered = en_GB
ckan.locales_filtered_out =
```

**Comment by amercader** [comment]
@maxious can you check your Jinja2 version? I suspect that it got updated somehow, and we should be using 2.6

**Comment by maxious** [comment]
Experiencing this again, with a fresh install of 2.4.1 rather than an upgrade. Only happens via apache/wsgi which suggests something to do with wsgi/virtualenv setup being incorrect... 

> pip install Jinja2==2.6
Requirement already satisfied (use --upgrade to upgrade): Jinja2==2.6 in /usr/lib/ckan/default/lib/python2.7/site-packages

> ls /usr/lib/python2.7/dist-packages/ | grep Jinja
Jinja2-2.7.2.egg-info

This is Amazon Linux 2015.09 and it seems to bundle jinja in the system (who knows why - there aren't any web apps included AFAIK).

**Comment by davidread** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it

**Comment by KrzysztofMadejski** [comment]
I've just checked and this error is dependent on Jinja2. It's ok with Jinja2 2.6, but appears with 2.7 onward. Support for new Jinja2s would be welcome as 2.7 corrects at least `filesizeformat` bug, which is used in `archiver`.

I see it was resolved in https://github.com/ckan/ckan/pull/3005.

It seems a bit arbitrary to get first node, or if it's a list first child of second node. If problems arise again I guess it would be better to iterate through node if it's a list and iterate through all child nodes.

**Comment by TkTech** [comment]
When I last tried bumping jinja up to tip I recall most of our jinja extensions breaking. Things like the node traversal API changing.

I ran out of time to work on it, but changing our snippet macro to rewrite `{% snippet %}` (not cached) into a `{% macro/call %}` (Jinja builtin, cached) since right now almost all cumulative CPU time in a deployment CKAN is spent re-parsing, re-compiling, and re-rendering snippets every single time they're called.

**Comment by davidread** [comment]
Sounds serious @TkTech - care to break this out into a separate issue and provide a bit more explanation?
